name: Deploy Alterações via FTP (DEV) 

on:
  push:
    branches:
      - developer
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instala o LFTP
        run: sudo apt-get -y install lftp

      - name: FTP Deploy para Bloomin Projetos
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST_BLOOMIN_PROJETOS }}
          username: ${{ secrets.FTP_USER_BLOOMIN_PROJETOS }}
          password: ${{ secrets.FTP_PASSWORD_BLOOMIN_PROJETOS }}
          server-dir: /brazilts-novo/

        env:
          lftp-settings: "set net:max-retries 3; set net:timeout 30; set xfer:parallel 1;"
